### ISSUE TITLE
Need to protect local values from garbage collection

### ISSUE THREAD

**Issue by phst** [aaptel/emacs-dynamic-module#43]
Module code can (indirectly) invoke the garbage collector. We need to make sure that in that case local values stay intact, i.e. all local values must be marked as GC roots while an environment is active.

I'd suggest to build up a stack of active environments, the values of which are marked as roots in the GC phase.

**Comment by aaptel** [comment]
Aw, I though we already had this figured out :/

Emacs uses conservative scanning the values are safe as long as they are used and appear somewhere in the stack, but indeed this is not guaranteed for local module values.

Your solution could work, its more-or-less the previous way Emacs handled the problem (linked list of GC roots) with the `GCPRO` macro. Alternatively we could just inhibit the GC (there's a "public" variable for that) while a module function is running but that's maybe too much.

**Comment by phst** [comment]
The stack scanning will most likely find values in the 'initial' frame because that's on the stack, but IIUC it won't find values in the other frames because they are malloced.
